[tool.poetry]
name = "logsentinel-sdk"
version = "0.1.0"
description = "Python SDK for structured, correlated logging from AWS Lambda functions"
authors = ["Arthur <arthur@logsentinel.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Xtazhoxton/logsentinel-sdk"
repository = "https://github.com/Xtazhoxton/logsentinel-sdk"
keywords = ["logging", "aws", "lambda", "observability", "kinesis"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: System :: Logging",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
package-mode = true
packages = [
    {include = "logsentinel_sdk", from = "src"}
]
include = ["src/logsentinel_sdk/py.typed"]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"
boto3 = "^1.42.61"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths =["tests"]
pythonpath =["src"]
addopts = "--cov=src/logsentinel_sdk --cov-report=term-missing"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
ruff = "^0.15.4"
mypy = "^1.19.1"
moto = {version = ">=5.1.21,<6.0.0", extras = ["dynamodb", "kinesis", "s3", "sqs", "ssm"]}
boto3-stubs = {extras = ["cloudformation", "dynamodb", "kinesis", "s3", "sqs", "ssm", "sts"], version = "^1.43.6"}

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.13"
strict = true